#!/bin/bash

c=1
while true
do
    if [ ! -e 256_$c ]; then
        break
    fi
    c=$[$c + 1]
done

## moving ic data from $HOME/music/
mv $HOME/music/ic.enzo 256_$c
cp $HOME/music/deltafunctions_ics_test.conf 256_$c/
cp $HOME/music/input_powerspec.txt 256_$c/
cp 256_1/SingleModeCosmology.enzo 256_$c/
cp 256_1/submit_enzo.sbatch 256_$c/
cp 256_1/submit_PSI.sbatch 256_$c/

## submit enzo job
cd 256_$c
sbatch submit_enzo.sbatch
